spring:
  application:
    name: mapservice
  datasource:
    port: 3306
    url: jdbc:mysql://localhost:3306/ProjectPokemonMaps
    database: ProjectPokemonMaps
    username: root
    password: root
    ssl: false
